### ISSUE TITLE
All calls are giving me HTTP 403 Forbidden

### ISSUE THREAD

**Issue by kirksl** [nickguimond/ZAPI#1]
Using Jira Cloud and Zephyr Cloud
I'm not using Zephyr's ZAPI Add-On
Clicked API Keys under Test -> Importer -> API Keys
In the upper left hand corner of the popup it shows "For bob.newhouse"
As well as the Access Key and Secret Key.  I copied both keys and the user name bob.newhouse

**I created a very simple call where "My Access Key" is the Access Key above and "My Secret Key" is the Secret Key above**
global.__ZAPIcreds = ["My Access Key", "My Secret Key", "bob.newhouse"];

var ZAPI = require('zephyr_api');
ZAPI.getServerInfo();

**I tried other calls which also fail with 403 Forbidden**
ZAPI.getLicenseInfo();
ZAPI.getGeneralInfo();
ZAPI.getAllCycles(10000, 10004); // verified these numbers in Jira

What am I doing wrong?

**Comment by nickguimond** [comment]
It only works with the zephyr for jira cloud add-on:
https://marketplace.atlassian.com/plugins/com.thed.zephyr.zapi/cloud/overview

sorry for the long delay in response
